// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tschfqnnxmywrkhpnyfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzY2hmcW5ueG15d3JraHBueWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzg2NDgsImV4cCI6MjA2Nzk1NDY0OH0.a8iJztskMtorIltcoQ0jneH2YQatudp0Szyoxrma418";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});